# LAB 1: Matrix and Vector Computations in python
In this lab you will use python to study the following topics:

- How to create matrices and vectors in python.

- How to manipulate matrices in python and create matrices of special types.

- How to add matrices and multiply a vector by a matrix by python.

- Solving System of Linear Equations Using Gaussian Elimination.

- Matrix Multiplication using Different views.

# First: you should run this cell

In [2]:
# Make all numpy available via shorter 'np' prefix
import numpy as np
import sympy as sym




# Question 1 :Declaring scalars, vectors, and matrices

a) Use [numpy.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html) to declare the following:

1. A scalar $s = 5$
2. A vector $v = \begin{bmatrix} 5  \\ -2 \\ 4  \\ \end{bmatrix}$
3. A matrix $A = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ 7 & 8 & 9  \\ \end{bmatrix}$
4. A matrix $B = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ \end{bmatrix}$
5. A matrix $C = \begin{bmatrix} 1 & 2   \\ 3 & 4  \\ 5 & 6   \\ \end{bmatrix}$

In [5]:
#type your code here:
s=np.array(5)

v=np.array([[5],
            [-2],
            [5]])

A=np.array([[1,2,3],
            [4,5,6],
            [7,8,9],])

B=np.array([[1,2,3],
            [4,5,6]])

C=np.array([[1,2],
            [3,4],
            [5,6]])

print("s = ",s)
print("v = \n",v)
print("A = \n",A)
print("B = \n",B)
print("C = \n",C)

s =  5
v = 
 [[ 5]
 [-2]
 [ 5]]
A = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
 [[1 2 3]
 [4 5 6]]
C = 
 [[1 2]
 [3 4]
 [5 6]]


b) Print the data type of $s, v,$ and $A$ using `type` command in python.

In [6]:
#type your code here:
print("type of s = ",type(s))
print("type of v = ",type(v))
print("type of A = ",type(A))

type of s =  <class 'numpy.ndarray'>
type of v =  <class 'numpy.ndarray'>
type of A =  <class 'numpy.ndarray'>


c) Using [numpy.shape](https://numpy.org/devdocs/reference/generated/numpy.shape.html) or `A.shape` print the shape of $s, v, A, B,$ and $C$.

In [7]:
#type your code here:
print("shape of s = ",s.shape)
print("shape of v = ",v.shape)
print("shape of A = ",A.shape)
print("shape of B = ",B.shape)
print("shape of C = ",C.shape)

shape of s =  ()
shape of v =  (3, 1)
shape of A =  (3, 3)
shape of B =  (2, 3)
shape of C =  (3, 2)


d) To access a given entry in the `numpy array` put the `row number - 1` and `column number - 1` in square brackets following the array name. Ex `a32 = A[2, 1]`.
- Print the value of the third row and the second column of the matrix $A$.
- Change it to $10$.
- Print the matrix A to check the entry is changed.

In [8]:
#type your code here:
print("A[2,1] = ",A[2,1])
A[2,1]=10
print("A = \n",A)

A[2,1] =  8
A = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]


e)To access a whole row or column of a matrix, use the colon operator. For example, `A[:, [1]]` is the second column of A, while `B[[1], :]` is the second row of B.

In [9]:
#type your code here:
print("A[:,[1]] = \n",A[:,[1]])
print("B[[1],:] = \n",B[[1],:])

A[:,[1]] = 
 [[ 2]
 [ 5]
 [10]]
B[[1],:] = 
 [[4 5 6]]


f) Type each of the following commands that generate special matrices:
- `np.eye(4), np.zeros(3), np.zeros((3, 1)), np.zeros((3, 5)), np.ones((2, 3)), and np.diag([4, 5, 6, 7])`

In [10]:
#type your code here:
print("np.eye(4) = \n",np.eye(4))
print("np.zeros(3) = \n",np.zeros(3))
print("np.zeros((3,1)) = \n",np.zeros((3,1)))
print("np.zeros((3,5)) = \n",np.zeros((3,5)))
print("np.ones((2,3)) = \n",np.ones((2,3)))
print("np.diag([4,5,6,7]) = \n",np.diag([4,5,6,7]))

np.eye(4) = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
np.zeros(3) = 
 [0. 0. 0.]
np.zeros((3,1)) = 
 [[0.]
 [0.]
 [0.]]
np.zeros((3,5)) = 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
np.ones((2,3)) = 
 [[1. 1. 1.]
 [1. 1. 1.]]
np.diag([4,5,6,7]) = 
 [[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]


# Question 2. Vectors Addition, Scaling, and dot product

a) Declare vectors $v1 = \begin{bmatrix} 1  \\ 2 \\ 7  \\ 4 \\ \end{bmatrix}$ and $v2 = \begin{bmatrix} 4  \\ 3 \\ 6  \\ 8 \\ \end{bmatrix}$

- Addition: $v1 + v2$
- Subtraction: $v1 - v2$
- Scaling by a number: $3 * v1$
- Scaling by a number: $v1 / 2$

In [11]:
#type your code here:
v1=np.array([[1],
            [2],
            [7],
            [4]])

v2=np.array([[4],
            [3],
            [6],
            [8]])

print("v1 + v2 = \n",v1+v2)
print("v1 - v2 = \n",v1-v2)
print("3 * v1 = \n",3*v1)
print("v1 / 2 = \n",v1/2)


v1 + v2 = 
 [[ 5]
 [ 5]
 [13]
 [12]]
v1 - v2 = 
 [[-3]
 [-1]
 [ 1]
 [-4]]
3 * v1 = 
 [[ 3]
 [ 6]
 [21]
 [12]]
v1 / 2 = 
 [[0.5]
 [1. ]
 [3.5]
 [2. ]]


b) Find the dot product between the two vectors $v1$ and $v2$ using the following:

- [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)
- [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy.matmul)
- `v1.T @ v2`

In [12]:
#type your code here:
print(f"using numpy.dot: {np.dot(v1.T,v2)}")
print(f"using numpy.matmul: {np.matmul(v1.T,v2)}")
print(f"using v1.T @ v2: {v1.T @ v2}")

using numpy.dot: [[84]]
using numpy.matmul: [[84]]
using v1.T @ v2: [[84]]


c) Find the length of the vectors $v1$ and $v2$.
- Using [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)
- Using the dot product and [numpy.sqrt](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html)


In [13]:
#type your code here:

print(f"length of v1 Using numpy.linalg.norm = {np.linalg.norm(v1)}")

print(f"length of v2 Using numpy.linalg.norm = {np.linalg.norm(v2)}")

print(f"length of v1 Using the dot product and numpy.sqrt = {np.sqrt(np.dot(v1.T,v1))}")

print(f"length of v2 Using the dot product and numpy.sqrt = {np.sqrt(np.dot(v2.T,v2))}")

length of v1 Using numpy.linalg.norm = 8.366600265340756
length of v2 Using numpy.linalg.norm = 11.180339887498949
length of v1 Using the dot product and numpy.sqrt = [[8.36660027]]
length of v2 Using the dot product and numpy.sqrt = [[11.18033989]]


d) Show that the vectors $u = \begin{bmatrix} 3  \\ 2 \\ -1  \\ 4 \\ \end{bmatrix}$ and $v = \begin{bmatrix} 1  \\ -1 \\ 1  \\ 0 \\ \end{bmatrix}$ are orthogonal.


In [14]:
#type your code here:
u=np.array([[3],
             [2],
             [-1],
             [4]])

v=v1=np.array([[1],
             [-1],
             [1],
             [0]])

print(f"u.T @ v = {np.dot(u.T,v)}")

u.T @ v = [[0]]


# Question 3. Matrix Addition and Matrix-Vector Multiplication

Declare vectors $u$ and $v$ and matrices $A$ and $B$ as following:
- $u = \begin{bmatrix} 2  \\ 7 \\ 2 \\ \end{bmatrix}$, $v = \begin{bmatrix} 8  \\ 2 \\ 4 \\ \end{bmatrix}$
- $A = \begin{bmatrix} 7 & 3 & 5  \\ 4 & 6 & 2 \\ \end{bmatrix}$, $B = \begin{bmatrix} 0 & 6 & 4  \\ 2 & 3 & 0 \\ \end{bmatrix}$

a) Calculate the following using python.

- $A+B$
- $B+A$
- $3A$
- $6B$
- $2(3B)$
- $6A+15B$
- $3(2A+5B)$
- $(3A^T)^T$

In [16]:
#type your code here:

u=np.array([[2],
            [7],
            [2]])

v=np.array([[8],
            [2],
            [4]])

a=np.array([[7,3,5],
            [4,6,2]])

b=np.array([[0,6,4],
            [2,3,0]])


print(f"u = \n{u}")

print(f"v = \n{v}")

print(f"A = \n{a}")

print(f"B = \n{b}")

print(f"A + B = \n{a+b}")

print(f"B + A = \n{b+a}")

print(f"3*A = \n{3*a}")

print(f"6*B = \n{6*b}")

print(f"2(3B) = \n{2*(3*b)}")

print(f"6A+15B = \n{(6*a)+(15*b)}")

print(f"3(2A+5B) = \n{3*((2*a)+(5*b))}")

print(f"3(3*A^T)^T = \n{(3*a.T).T}")


u = 
[[2]
 [7]
 [2]]
v = 
[[8]
 [2]
 [4]]
A = 
[[7 3 5]
 [4 6 2]]
B = 
[[0 6 4]
 [2 3 0]]
A + B = 
[[7 9 9]
 [6 9 2]]
B + A = 
[[7 9 9]
 [6 9 2]]
3*A = 
[[21  9 15]
 [12 18  6]]
6*B = 
[[ 0 36 24]
 [12 18  0]]
2(3B) = 
[[ 0 36 24]
 [12 18  0]]
6A+15B = 
[[ 42 108  90]
 [ 54  81  12]]
3(2A+5B) = 
[[ 42 108  90]
 [ 54  81  12]]
3(3*A^T)^T = 
[[21  9 15]
 [12 18  6]]


b) To obtain the matrix-vector product $Au$ using python, type `A @ u`. Calculate the following:

- $Au+Av$
- $A(u+v)$
- $(A+B)u$
- $Au+Bu$
- $A(3u)$
- $3A(u)$

In [17]:
#type your code here:
print(f"Au + Av = \n{(a@u)+(a@v)}")

print(f"A(u + v) = \n{a@(u+v)}")

print(f"(A + B)u = \n{(a+b)@u}")

print(f"Au + Bu = \n{(a@u)+(b@u)}")

print(f"A(3u) = \n{a@(3*u)}")

print(f"3A(u) = \n{(3*a)@(u)}")

Au + Av = 
[[127]
 [106]]
A(u + v) = 
[[127]
 [106]]
(A + B)u = 
[[95]
 [79]]
Au + Bu = 
[[95]
 [79]]
A(3u) = 
[[135]
 [162]]
3A(u) = 
[[135]
 [162]]


# Question 4. Gaussian Elimination and Reduced Row-Echelon Form

You will see a step-by-step example of the row operations that transform a matrix $A$ into its reduced row echelon form $R = rref(A)$. In this demonstration, each pivot is chosen to be the largest in its column (for numerical stability), so extra row interchanges are used. Since $rref(A)$ is uniquely determined by $A$, this does not affect the final answer.

The built in [rref](https://docs.sympy.org/latest/tutorial/matrices.html#rref) method `sympy.rref()` method just search for the method and its output to deal with the code.

#### (a) Generate and display a $3 \times 4$ matrix $A$ with random integer entries 

In [34]:
#type your code here:
A = np.fix((10*(np.random.rand(3,4))))
print("\n A = \n", A)


 A = 
 [[3. 7. 3. 2.]
 [0. 8. 9. 1.]
 [1. 5. 1. 5.]]


- To transform $A$ into $R = rref(A)$, start with $R = A$.
- Normalize the first row of R to get R(1st row, 1st column) = 1

    - `R = A`
    - `R[0,:] = R[0, :] / R[0, 0]`

(note the use of the colon to operate on whole rows of the matrix). 

<div class="alert alert-block alert-warning">If your random matrix happens to have A(1, 1) = 0, then interchange rows to get a nonzero entry in the (1, 1) position before doing the calculation above.</div>

- Now subtract a multiple of the first row of R from the second row to make R(2, 1) = 0:

    - `R[1, :] = R[1, :] - R[1, 0] * R[0, :]`

- Repeat this procedure to make R(3, 1) = 0:

    - `R[2, :] = R[2, :] - R[2, 0] * R[0, :]`

The first column of your matrix $R$ should now be the same as the first column of $rref(A)$.

In [35]:
#type your code here:
R=A
R[0,:]=R[0, :] / R[0,0]

R[1, :]=R[1, :] - R[1,0] * R[0,:]

R[2,:]=R[2,:]-R[2,0]*R[0,:]

print(f"R = {R}")

R = [[1.         2.33333333 1.         0.66666667]
 [0.         8.         9.         1.        ]
 [0.         2.66666667 0.         4.33333333]]


#### (b)Operate on $R$ by the same method as in (a) to obtain the second column of $rref(A)$. First normalize row $2$ of $R$, then subtract multiples of row $2$ from rows $1$ and $3$ to put zeros in the (1, 2) and (3, 2) positions. Be sure to refer to the entries in your matrix symbolically as was done in part (a)

In [36]:
# Normalize row 2 (make pivot 1 at (2,2))
R[1, :] = R[1, :] / R[1, 1]
R[0, :] = R[0, :] - R[0, 1] * R[1, :]
R[2, :] = R[2, :] - R[2, 1] * R[1, :]
print(f"R = {R}")

R = [[ 1.     0.    -1.625  0.375]
 [ 0.     1.     1.125  0.125]
 [ 0.     0.    -3.     4.   ]]


#### (c) Operate on $R$ by the same method as in (b) to obtain the third column of $rref(A)$. First normalize row $3$ of $R$, then subtract multiples of row $3$ from rows $1$ and $2$ to put zeros in the (1, 3) and (2, 3) positions.

In [37]:
#type your code here:

R[2, :] = R[2, :] / R[2, 2]
R[0, :] = R[0, :] - R[0, 2] * R[2, :]
R[1, :] = R[1, :] - R[1, 2] * R[2, :]

print(f"R = {R}")

R = [[ 1.          0.          0.         -1.79166667]
 [ 0.          1.          0.          1.625     ]
 [-0.         -0.          1.         -1.33333333]]


#### (d) Your matrix $R$ should now be transformed into $rref(A)$ (since $A$ is a random $3 \times 4$ matrix, $rref(A)$ is (almost) sure to have rank (3) `np.linalg.matrix_rank(R)`. Check your answer by python with the rref method . If the answer is not the same as the current value of your $R$, go back and redo your calculations.

- use the the built in rref method `sympy.rref()`
- print the output matrix in numpy array type

    - `M = sym.Matrix(A)`
    - `M_rref = M.rref()`
    - `R = np.array((M_rref[0])).astype(np.float64)`

In [38]:
#type your code here:

# Use sympy.rref() method 
M=sym.Matrix(A)
M_r=M.rref()
R= np.array((M_r[0])).astype(np.float64)
print(f"R = {R}")

R = [[ 1.          0.          0.         -1.79166667]
 [ 0.          1.          0.          1.625     ]
 [ 0.          0.          1.         -1.33333333]]


# Question 5. Matrix Multiplication using Different views

we discussed in the lecture four different ways about product $AB = C$ where $A$ and $B$ are arbitry matrices. If $A$ is an $m \times n$ matrix and $B$ is an $n \times p$ matrix, then $C$ is an $m \times p$ matrix:

1. **Standard(row times column):** The standard way of describing a matrix product is to say that $c_(ij)$ equals the dot product of row $i$ of matrix $A$ and column $j$ of matrix $B$. 
 
2. **Columns:** The product of matrix $A$ and column $j$ of matrix $B$ equals column $j$ of matrix  $C$. This tells us that the columns of $C$ are combinations of columns of $A$.

3. **Rows:** The product of row $i$ of matrix $A$ and matrix $B$ equals row $i$ of matrix $C$.So the rows of $C$ are combinations of rows of $B$.

4. **Column times row**: A column of $A$ is an $m \times 1$ vector and a row of $B$ is a $1 \times p$ vector.Their product is a matrix.

In this problem we will use python to perform the matrix multiplication using these different ways, and compute the execution time for each method time.

(Write your code as a function that perform the multiplication for arbitrary size of the matrices $A$ and $B$)

In [27]:
def check_dimension(A, B):
    return A.shape[1] == B.shape[0]

def mat_mul_standard(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
    m, n = A.shape
    n, p = B.shape
    C = np.zeros((m, p))
    # Standard triple-loop implementation (row x column)
    for i in range(m):
        for j in range(p):
            s = 0.0
            for k in range(n):
                s += A[i, k] * B[k, j]
            C[i, j] = s
    return C

def mat_mul_columns(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
    m, n = A.shape
    n, p = B.shape
    C = np.zeros((m, p))
    # Build C by computing each column as a linear combination of A's columns
    for j in range(p):
        for k in range(n):
            C[:, j] += B[k, j] * A[:, k]
    return C

def mat_mul_rows(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
    m, n = A.shape
    n, p = B.shape
    C = np.zeros((m, p))
    # Build C row-by-row: each row is combination of B's rows
    for i in range(m):
        for k in range(n):
            C[i, :] += A[i, k] * B[k, :]
    return C

def mat_mul_column_times_row(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
    m, n = A.shape
    n, p = B.shape
    C = np.zeros((m, p))
    # Sum outer products of columns of A and rows of B
    for k in range(n):
        C += np.outer(A[:, k], B[k, :])
    return C

In [28]:
#A = np.array([[12., 7., 3.],[4., 5., 6.],[7., 8., 9.]])
#B = np.array([[5., 8., 1., 2.],[6., 7., 3., 0.],[4., 5., 9., 1.]])

A = np.fix((10*(np.random.rand(300, 300))))
B = np.fix((10*(np.random.rand(300, 300))))

In [29]:
%%time
print('A @ B = \n', A @ B)

A @ B = 
 [[6042. 6059. 6007. ... 6079. 5573. 5917.]
 [5897. 6577. 5841. ... 6256. 5688. 6248.]
 [5561. 5862. 5580. ... 6007. 5309. 5495.]
 ...
 [5874. 6444. 5817. ... 6694. 5733. 5985.]
 [5806. 6143. 5582. ... 6225. 5446. 6038.]
 [6001. 6586. 6019. ... 6392. 5605. 6171.]]
CPU times: user 6.55 ms, sys: 19 µs, total: 6.57 ms
Wall time: 7.29 ms


In [30]:
%%time
C_standard = mat_mul_standard(A, B)
print('C_standard = \n', C_standard)

C_standard = 
 [[6042. 6059. 6007. ... 6079. 5573. 5917.]
 [5897. 6577. 5841. ... 6256. 5688. 6248.]
 [5561. 5862. 5580. ... 6007. 5309. 5495.]
 ...
 [5874. 6444. 5817. ... 6694. 5733. 5985.]
 [5806. 6143. 5582. ... 6225. 5446. 6038.]
 [6001. 6586. 6019. ... 6392. 5605. 6171.]]
CPU times: user 12.7 s, sys: 7.4 ms, total: 12.7 s
Wall time: 12.8 s


In [31]:
%%time
C_columns = mat_mul_columns(A, B)
print('C_columns = \n', C_columns)

C_columns = 
 [[6042. 6059. 6007. ... 6079. 5573. 5917.]
 [5897. 6577. 5841. ... 6256. 5688. 6248.]
 [5561. 5862. 5580. ... 6007. 5309. 5495.]
 ...
 [5874. 6444. 5817. ... 6694. 5733. 5985.]
 [5806. 6143. 5582. ... 6225. 5446. 6038.]
 [6001. 6586. 6019. ... 6392. 5605. 6171.]]
CPU times: user 553 ms, sys: 2.95 ms, total: 556 ms
Wall time: 571 ms


In [32]:
%%time
C_rows = mat_mul_rows(A, B)
print('C_rows = \n', C_rows)

C_rows = 
 [[6042. 6059. 6007. ... 6079. 5573. 5917.]
 [5897. 6577. 5841. ... 6256. 5688. 6248.]
 [5561. 5862. 5580. ... 6007. 5309. 5495.]
 ...
 [5874. 6444. 5817. ... 6694. 5733. 5985.]
 [5806. 6143. 5582. ... 6225. 5446. 6038.]
 [6001. 6586. 6019. ... 6392. 5605. 6171.]]
CPU times: user 484 ms, sys: 2.87 ms, total: 487 ms
Wall time: 503 ms


In [33]:
%%time
C_column_times_row = mat_mul_column_times_row(A, B)
print('C_column_times_row = \n', C_column_times_row)

C_column_times_row = 
 [[6042. 6059. 6007. ... 6079. 5573. 5917.]
 [5897. 6577. 5841. ... 6256. 5688. 6248.]
 [5561. 5862. 5580. ... 6007. 5309. 5495.]
 ...
 [5874. 6444. 5817. ... 6694. 5733. 5985.]
 [5806. 6143. 5582. ... 6225. 5446. 6038.]
 [6001. 6586. 6019. ... 6392. 5605. 6171.]]
CPU times: user 62.8 ms, sys: 0 ns, total: 62.8 ms
Wall time: 63.1 ms
